#
#Sat Oct 03 00:34:09 COT 2026
acceptInsecureCerts=true
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, test-type, no-sandbox, ignore-certificate-errors, --window-size\=1440,900, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, disable-dev-shm-usage, disable-extensions, disable-translate, disable-notifications, remote-allow-origins\=*, --headless\=chrome, --headless], extensions\=[], prefs\={credentials_enable_service\=false, profile.password_manager_enabled\=false, profile.password_manager_leak_detection\=false}}
